path_classifiers:
  generated:
    exclude: "root/include/hypercomm/tasking/tasking.decl.h"
extraction:
  cpp:
    configure:
      command: "./prepare_deps"
    before_index: "export CHARM_HOME=$LGTM_SRC/charm"
    index:
      build_command:
      - "cmake ."
      - "make -j2"
