path_classifiers:
  generated:
    - build
extraction:
  cpp:
    configure:
      command: "./prepare_deps"
    before_index: "export CHARM_HOME=$LGTM_SRC/charm"
    index:
      build_command:
      - "cmake -H. -Bbuild/"
      - "cd build"
      - "make -j2"
