# This is a basic workflow to help you get started with Actions

name: SMP

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Build Charm++
    - name: build-charm++
      run: |
        git clone https://github.com/UIUC-PPL/charm.git
        cd charm
        ./build charm++ netlrts-linux-x86_64 smp -g -j2 --with-production --enable-error-checking


    # Build Hypercomm
    - name: prep-hypercomm
      run: |
        export CHARM_HOME=$GITHUB_WORKSPACE/charm
        cmake -H. -Bbuild/
        cd build
        make

    # Test Hypercomm
    - name: test-hypercomm
      run: |
        export CHARM_HOME=$GITHUB_WORKSPACE/charm
        export OPTS="-O2 -g3"
        echo "<!-- redn_demo --!>"
        cd tests/redn_demo
        TESTOPTS="++local ++ppn 2 65" make test
        TESTOPTS="++local ++ppn 2 129" make test
        TESTOPTS="++local 65" make test
        TESTOPTS="++local 129" make test
        echo "<!-- bcast_demo --!>"
        cd ../bcast_demo
        TESTOPTS="++local 65" make test
        TESTOPTS="++local 129" make test
        echo "<!-- tree_demo --!>"
        cd ../tree_demo
        TESTOPTS="++local" make test
        echo "<!-- future_demo --!>"
        cd ../future_demo
        TESTOPTS="++local ++ppn 2 65" make test
        TESTOPTS="++local ++ppn 2 129" make test
        TESTOPTS="++local 65" make test
        TESTOPTS="++local 129" make test
        echo "<!-- sdag_demo --!>"
        cd ../sdag_demo
        TESTOPTS="++local ++ppn 2 65" make test
        TESTOPTS="++local ++ppn 2 129" make test
        TESTOPTS="++local 65" make test
        TESTOPTS="++local 129" make test
        echo "<!-- task_demo --!>"
        cd ../task_demo
        TESTOPTS="++local -nn" make test
        TESTOPTS="++local -np" make test
        TESTOPTS="++local -nd 4" make test
        echo "<!-- lb_demo --!>"
        cd ../lb_demo
        TESTOPTS="++local" make test
        echo "<!-- avalanche --!>"
        cd ../avalanche
        TESTOPTS="++local 65" DEBUG=1 make test
        TESTOPTS="++local ++ppn 2 65" DEBUG=1 make test
